### ISSUE TITLE
Cannot read property 'userAgent' of undefined when using run.node on the server

### ISSUE THREAD

**Issue by jdh7190** [runonbitcoin/sdk#7]
I receive the following error when trying to require run-sdk on a server side .js file like so:
```javascript
const Run = require('run-sdk');
```
```
node_modules\run-sdk\dist\run.node.js:5734
        const t = window.navigator.userAgent;
                                   ^

TypeError: Cannot read property 'userAgent' of undefined
    at s (C:\Users\jhens\node\windbell_2\windbell\node_modules\run-sdk\dist\run.node.js:5734:36)
    at Object.Rt (C:\Users\jhens\node\windbell_2\windbell\node_modules\run-sdk\dist\run.node.js:5743:23)
    at Object.<anonymous> (C:\Users\jhens\node\windbell_2\windbell\node_modules\run-sdk\dist\run.node.js:7068:11)
    at n (C:\Users\jhens\node\windbell_2\windbell\node_modules\run-sdk\dist\run.node.js:11:21)
    at C:\Users\jhens\node\windbell_2\windbell\node_modules\run-sdk\dist\run.node.js:45:18
    at Object.<anonymous> (C:\Users\jhens\node\windbell_2\windbell\node_modules\run-sdk\dist\run.node.js:46:2)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\jhens\node\windbell_2\windbell\server.js:15:13)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
[nodemon] app crashed - waiting for file changes before starting...
```
This appears to be due to a check for the ```window``` object that seems unnecessary in the node version of run.

In the un-minified version of the file, the code is in the following block: (line 5734)

```javascript
function s() {
        if ("undefined" == typeof window) return;
        const t = window.navigator.userAgent;
        if (-1 !== t.indexOf("MSIE") || -1 !== t.indexOf("Trident")) throw new Error("Run is not supported on Internet Explorer. Please upgrade to Edge.");
        if (/iP(hone|od|ad)/.test(navigator.platform)) {
            var e = navigator.appVersion.match(/OS (\d+)_(\d+)_?(\d+)?/);
            if ([parseInt(e[1], 10), parseInt(e[2], 10), parseInt(e[3] || 0, 10)][0] < 13) throw new Error("Run is not supported on this iOS version. Please upgrade to iOS 13 or above.")
        }
    }
```

**Comment by brentongunning** [comment]
Thanks @jdh7190 . This should be fixed in 0.6.18. Please re-open if you still see it.

https://github.com/runonbitcoin/sdk/commit/fb26e69607ede25c69995b4e63c2a8e25767ac35
